AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-file-uploader

  Sample SAM Template for sam-file-uploader

Globals:
  Environment:
    Variables:
      FILES_BUCKET_NAME: !Ref FilesBucket
  Function:
    Timeout: 3
Resources:
  FileUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.fileHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Events:
        FileUploadApi:
          Type: Api
          Properties:
            Path: /upload
            Method: post
      Policies:
        - S3FullAccessPolicy:
            Bucket: !Ref FilesBucket
  S3EventHandlerFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.handler
      Runtime: nodejs20.x
      CodeUri: .
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: S3EventsQueue
      Policies:
        - SQSPollerPolicy:
            QueueName: S3EventsQueue
        - S3ReadAccessPolicy:
            Bucket: !Ref FilesBucket
  FilesBucket:
    Type: AWS:S3:Bucket
    Properties:
      BucketName: 'FilesBucket'
  S3EventsQueue:
    Type: AWS:SQS:Queue
    Properties:
      QueueName: S3EventsQueue
  S3EventNotification:
    Type: 'AWS::S3::BucketNotification'
    Properties:
      Bucket: !Ref FilesBucket
      NotificationConfiguration:
        QueueConfigurations:
          - Event: 's3:ObjectCreated:*'
            Queue: !GetAtt S3EventsQueue.Arn
