AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-file-uploader

  Sample SAM Template for sam-file-uploader

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        FILES_BUCKET_NAME: !Ref FilesBucket
Resources:
  FileUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/app.fileHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Events:
        FileUploadApi:
          Type: Api
          Properties:
            Path: /upload
            Method: post
      Policies:
        - S3FullAccessPolicy:
            BucketName: FilesBucket
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - src/app.ts
  S3EventHandlerFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/app.handler
      Runtime: nodejs20.x
      CodeUri: .
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: S3EventsQueue
      Policies:
        - SQSPollerPolicy:
            QueueName: S3EventsQueue
        - S3ReadAccessPolicy:
            Bucket: !Ref FilesBucket
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - src/app.ts
  FilesBucket:
    Type: AWS:S3:Bucket
    Properties:
      BucketName: FilesBucket
  S3EventsQueue:
    Type: AWS:SQS:Queue
    Properties:
      QueueName: S3EventsQueue
  S3EventNotification:
    Type: 'AWS::S3::BucketNotification'
    Properties:
      Bucket: !Ref FilesBucket
      NotificationConfiguration:
        QueueConfigurations:
          - Event: 's3:ObjectCreated:*'
            Queue: !GetAtt S3EventsQueue.Arn
